version: '3.8' 

services:
  voice-collection-app:

    build: .
    
    image: voice-collection-app:latest
    
    restart: always

    ports:
      - "80:5000"
      
    volumes:
      - ./data:/app/data
      - ./static/audios-tmz-final:/app/static/audios-tmz-final
      - ./static/audios-darija-final:/app/static/audios-darija-final
      
    environment:
      - FLASK_ENV=production 
      - ADMIN_USER=admin
      - ADMIN_PASS=password123
      - FLASK_SECRET_KEY=une_cle_secrete_longue_et_aleatoire_pour_la_prod

networks:
  default:
    name: voice-collection-network